openapi: 3.1.0
info:
  title: OpenAQ Averages Readme API
  description: '

    OpenAQ is a nonprofit organization providing universal access to air

    quality data to empower a global community of changemakers to solve air

    inequality-the unequal access to clean air.'
  version: 2.0.0
tags:
- name: Readme
paths:
  /v2/sources/readme/{slug}:
    get:
      tags:
      - Readme
      summary: OpenAQ Source Readme
      description: Provides a readme for a given source by the source slug
      operationId: readme_get_v2_sources_readme__slug__get
      deprecated: true
      security:
      - APIKeyHeader: []
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
          examples:
          - london_mobile
          title: Slug
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: X-API-Key
